# 参考 https://github.com/rails/rails/blob/main/.rubocop.yml
## rubocop 関連の gem を require 
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'

## && と || を強制するために有効化
Style/AndOr:
  Enabled: true

## 日本語コメントを許可します。
Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CommentIndentation:
  Enabled: false

# https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutemptylinesaroundattributeaccessor
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutspacearoundmethodcalloperator
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintdeprecatedopensslconstant
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_lint/#lintraiseexception
Lint/RaiseException:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_lint/#lintstructnewoverride
Lint/StructNewOverride:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - 'lib/tasks/dev.rake'

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'Guardfile'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'app/views/**/*.jbuilder'
    - 'lib/tasks/dev.rake'

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'lib/tasks/dev.rake'

Metrics/ModuleLength:
  CountComments: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Naming/MethodParameterName:
  AllowedNames: [e]

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# https://rubocop.readthedocs.io/en/stable/cops_style/#styleblockdelimiters
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# https://rubocop.readthedocs.io/en/stable/cops_style/#styleexponentialnotation
Style/ExponentialNotation:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_style/#stylehasheachmethods
Style/HashEachMethods:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_style/#stylehashtransformkeys
Style/HashTransformKeys:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_style/#stylehashtransformvalues
Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

# https://rubocop.readthedocs.io/en/stable/cops_style/#styleslicingwithrange
Style/SlicingWithRange:
  Enabled: true

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/SpaceInsideBlockBraces
Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
